import { useState } from "react";
import { getPredictions, getStates, getModelInfo } from "../services/api";
import { useFetch } from "../hooks/useFetch";
import { Badge, Card, EmptyNote, ErrorBanner, PageHead, Spinner, StatChip } from "../components/ui";
import { ChipIcon, DatabaseIcon, ListIcon, RefreshIcon, ThermometerIcon } from "../components/icons";

const LIMIT_OPTIONS = [25, 50, 100];

function prettyDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString(undefined, {
    day: "numeric",
    month: "short",
    year: "numeric",
    timeZone: "UTC",
  });
}

export function PredictionHistoryPage() {
  const states = useFetch(getStates, []);
  const modelInfo = useFetch(getModelInfo, []);
  const [limit, setLimit] = useState(50);
  const [stateFilter, setStateFilter] = useState("");
  const [records, setRecords] = useState<PageState>({ rows: [], exhausted: false });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loadedOnce, setLoadedOnce] = useState(false);

  interface PageState {
    rows: {
      id: number;
      state: string;
      district?: string;
      location?: string;
      forecast_date: string;
      predicted_temp_avg: number[];
      created_at: string;
    }[];
    exhausted: boolean;
  }

  async function load(reset: boolean) {
    setLoading(true);
    setError(null);
    try {
      const offset = reset ? 0 : records.rows.length;
      const resp = await getPredictions(limit, offset);
      setRecords({
        rows: reset ? resp.predictions : [...records.rows, ...resp.predictions],
        exhausted: resp.predictions.length < limit,
      });
      setLoadedOnce(true);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }

  const visible = stateFilter
    ? records.rows.filter((r) => r.state === stateFilter)
    : records.rows;

  return (
    <div className="page">
      <PageHead
        title="Prediction History"
        desc="Every forecast generated through the API is stored in PostgreSQL and listed here — an audit trail of real model outputs."
      />

      <Card title="Stored predictions" icon={<ListIcon />}>
        <div className="toolbar">
          <label className="field inline">
            <span>State filter</span>
            <select value={stateFilter} onChange={(e) => setStateFilter(e.target.value)}>
              <option value="">All states</option>
              {states.data?.states.map((s) => (
                <option key={s} value={s}>
                  {s}
                </option>
              ))}
            </select>
          </label>

          <label className="field inline">
            <span>Page size</span>
            <select
              value={limit}
              onChange={(e) => {
                setLimit(Number(e.target.value));
                setRecords({ rows: [], exhausted: false });
                setLoadedOnce(false);
              }}
            >
              {LIMIT_OPTIONS.map((n) => (
                <option key={n} value={n}>
                  {n}
                </option>
              ))}
            </select>
          </label>

          <button className="btn-secondary" onClick={() => void load(true)} disabled={loading}>
            <RefreshIcon />
            {loading ? "Loading predictions…" : loadedOnce ? "Refresh" : "Load predictions"}
          </button>
        </div>

        {loadedOnce && records.rows.length > 0 && (
          <div className="stat-chips" style={{ marginBottom: 16 }}>
            <StatChip
              icon={<ThermometerIcon />}
              label="Predictions loaded"
              value={records.rows.length.toLocaleString()}
            />
            {stateFilter && (
              <StatChip
                icon={<DatabaseIcon />}
                label={`Matching ${stateFilter}`}
                value={visible.length.toLocaleString()}
              />
            )}
            {modelInfo.data && (
              <StatChip
                icon={<ChipIcon />}
                label="Generated by"
                value={modelInfo.data.model_name}
              />
            )}
          </div>
        )}

        {error && <ErrorBanner message={error} />}
        {loadedOnce && !loading && visible.length === 0 && !error && (
          <EmptyNote
            title={stateFilter ? `No loaded predictions for ${stateFilter}` : "No predictions yet"}
            hint={
              stateFilter
                ? "More records may exist for other states — load more or clear the filter."
                : "No predictions have been generated so far. Create one on the Forecast page."
            }
          />
        )}
        {!loadedOnce && !loading && !error && (
          <EmptyNote
            title="Prediction history not loaded"
            hint="Click “Load predictions” to fetch the stored forecast records from the backend."
          />
        )}

        {visible.length > 0 && (
          <>
            <div className="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th className="num">ID</th>
                    <th>State</th>
                    <th>District</th>
                    <th>Location</th>
                    <th>Forecast Date</th>
                    <th className="num">Predicted Temperature (°C)</th>
                    <th>Created At</th>
                  </tr>
                </thead>
                <tbody>
                  {visible.map((r) => (
                    <tr key={r.id}>
                      <td className="num">{r.id}</td>
                      <td>
                        <Badge>{r.state}</Badge>
                      </td>
                      <td>{r.district || <Badge neutral>—</Badge>}</td>
                      <td>{r.location || <Badge neutral>—</Badge>}</td>
                      <td title={r.forecast_date}>{prettyDate(r.forecast_date)}</td>
                      <td className="num strong" style={{ fontSize: '0.9em' }}>
                        {Array.isArray(r.predicted_temp_avg) ? (
                          <span title={r.predicted_temp_avg.map(v => v.toFixed(1)).join(", ")}>
                            {r.predicted_temp_avg.slice(0, 3).map(v => v.toFixed(1)).join(", ")}
                            {r.predicted_temp_avg.length > 3 ? "..." : ""}
                          </span>
                        ) : (
                          // Fallback for older scalar data if it somehow reaches the frontend
                          Number(r.predicted_temp_avg).toFixed(1)
                        )}
                      </td>
                      <td>{new Date(r.created_at).toLocaleString()}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="chart-note">
              Showing {visible.length} loaded record(s)
              {stateFilter && ` (filtered from ${records.rows.length})`}. The backend returns one
              page at a time and does not report a total count.
            </p>
            <div className="load-more">
              <button
                className="btn-secondary"
                onClick={() => void load(false)}
                disabled={loading || records.exhausted}
              >
                {records.exhausted ? "All loaded records shown" : "Load more"}
              </button>
            </div>
          </>
        )}

        {loading && <Spinner label="Loading predictions…" />}
      </Card>
    </div>
  );
}
