import { useState } from "react";
import { getPredictions, getStates, getModelInfo } from "../services/api";
import { useFetch } from "../hooks/useFetch";
import { Card, EmptyNote, ErrorBanner, Spinner } from "../components/ui";

const LIMIT_OPTIONS = [25, 50, 100];

export function PredictionHistoryPage() {
  const states = useFetch(getStates, []);
  const modelInfo = useFetch(getModelInfo, []);
  const [limit, setLimit] = useState(50);
  const [stateFilter, setStateFilter] = useState("");
  const [records, setRecords] = useState<PageState>({ rows: [], exhausted: false });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loadedOnce, setLoadedOnce] = useState(false);

  interface PageState {
    rows: {
      id: number;
      state: string;
      district?: string;
      location?: string;
      forecast_date: string;
      predicted_temp_avg: number;
      created_at: string;
    }[];
    exhausted: boolean;
  }

  async function load(reset: boolean) {
    setLoading(true);
    setError(null);
    try {
      const offset = reset ? 0 : records.rows.length;
      const resp = await getPredictions(limit, offset);
      setRecords({
        rows: reset ? resp.predictions : [...records.rows, ...resp.predictions],
        exhausted: resp.predictions.length < limit,
      });
      setLoadedOnce(true);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }

  const visible = stateFilter
    ? records.rows.filter((r) => r.state === stateFilter)
    : records.rows;

  return (
    <div className="page">
      <Card title="Prediction history (stored in PostgreSQL)">
        <div className="toolbar">
          <label className="field inline">
            <span>State filter</span>
            <select value={stateFilter} onChange={(e) => setStateFilter(e.target.value)}>
              <option value="">All states</option>
              {states.data?.states.map((s) => (
                <option key={s} value={s}>
                  {s}
                </option>
              ))}
            </select>
          </label>

          <label className="field inline">
            <span>Page size</span>
            <select
              value={limit}
              onChange={(e) => {
                setLimit(Number(e.target.value));
                setRecords({ rows: [], exhausted: false });
                setLoadedOnce(false);
              }}
            >
              {LIMIT_OPTIONS.map((n) => (
                <option key={n} value={n}>
                  {n}
                </option>
              ))}
            </select>
          </label>

          <button className="btn-secondary" onClick={() => void load(true)} disabled={loading}>
            {loading ? "Loading predictions…" : loadedOnce ? "Refresh" : "Load predictions"}
          </button>
        </div>

        {modelInfo.data && (
          <p className="chart-note">
            All predictions were generated by <strong>{modelInfo.data.model_name}</strong>{" "}
            (target: {modelInfo.data.target}). The prediction table does not store a per-row
            model field, so the model is shown here once rather than per row.
          </p>
        )}

        {error && <ErrorBanner message={error} />}
        {loadedOnce && !loading && visible.length === 0 && !error && (
          <EmptyNote
            text={
              stateFilter
                ? `No loaded predictions for ${stateFilter}. More records may exist — load more or clear the filter.`
                : "No predictions have been generated yet. Create one on the Forecast page."
            }
          />
        )}

        {visible.length > 0 && (
          <>
            <div className="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>State</th>
                    <th>District</th>
                    <th>Location</th>
                    <th>Forecast Date</th>
                    <th>Predicted Temperature (°C)</th>
                    <th>Created At</th>
                  </tr>
                </thead>
                <tbody>
                  {visible.map((r) => (
                    <tr key={r.id}>
                      <td>{r.id}</td>
                      <td>{r.state}</td>
                      <td>{r.district || "-"}</td>
                      <td>{r.location || "-"}</td>
                      <td>{r.forecast_date}</td>
                      <td>{r.predicted_temp_avg.toFixed(2)}</td>
                      <td>{new Date(r.created_at).toLocaleString()}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="chart-note">
              Showing {visible.length} loaded record(s){stateFilter && ` (filtered from ${records.rows.length})`}
              . The backend returns one page at a time and does not report a total count.
            </p>
            <div className="load-more">
              <button
                className="btn-secondary"
                onClick={() => void load(false)}
                disabled={loading || records.exhausted}
              >
                {records.exhausted ? "All loaded records shown" : "Load more"}
              </button>
            </div>
          </>
        )}

        {loading && <Spinner label="Loading predictions…" />}
      </Card>
    </div>
  );
}
